name: wechat_camera_picker
version: 4.3.6
description: |
  A camera picker for Flutter projects based on WeChat's UI,
  which is also a separate runnable extension to the
  wechat_assets_picker.
topics:
  - picker
  - camera
  - image
  - video
  - wechat

repository: https://github.com/fluttercandies/flutter_wechat_camera_picker
issue_tracker: https://github.com/fluttercandies/flutter_wechat_camera_picker/issues

environment:
  sdk: ^3.2.0
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  wechat_picker_library: 

  camera: 
  camera_android: 
  camera_platform_interface: 

  collection: '>=1.18.0 <2.0.0'
  path: ^1.8.4
  photo_manager: 
  photo_manager_image_provider: 
  sensors_plus: 
  video_player: 

dev_dependencies:
  flutter_lints: any

screenshots:
  - description: 'Screenshot 1'
    path: screenshots/README_1.jpg
  - description: 'Screenshot 2'
    path: screenshots/README_2.jpg
  - description: 'Screenshot 3'
    path: screenshots/README_3.jpg
  - description: 'Screenshot 4'
    path: screenshots/README_4.jpg
  - description: 'Screenshot 5'
    path: screenshots/README_5.jpg
